language: php

php:
    - 7.0
    - 7.1

matrix:
  allow_failures:
    - php: hhvm

before_script:
    - touch .env
    - echo "DB_CONNECTION=sqlite" >> .env
    - touch database/database.sqlite
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev
    - php artisan key:generate
    - php artisan migrate --database=testing --force
script:
    - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)